[workspace]
authors = ["Tien Chueh Wang <f74169@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "miniaudio-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
run = "mojo main.mojo"

[dependencies]
mojo = ">=1.0.0b2.dev2026051006,<2"
