from miniaudio_contract_assertions import expect_negative, expect_nonzero, expect_zero
from miniaudio_ctypes import MiniAudioCtypes


def run_mojo_decoder_encoder_contract_suite() raises:
    var bridge = MiniAudioCtypes("./build/libminiaudio_mojo.so")
    var null_ptr = OpaquePointer[MutExternalOrigin](unsafe_from_address=Int(0))
    var test_wav = "./build/test_assets/sine_440_stereo.wav"

    var decoder = bridge.decoder_create()
    if decoder == null_ptr:
        raise Error("decoder_create failed in decoder/encoder contract suite")

    var encoder = bridge.encoder_create()
    if encoder == null_ptr:
        bridge.decoder_destroy(decoder)
        raise Error("encoder_create failed in decoder/encoder contract suite")

    # Deterministic decoder contracts.
    expect_nonzero(
        "decoder_init_file_f32(missing)",
        bridge.decoder_init_file_f32(decoder, "/tmp/mmj-definitely-missing.wav", UInt32(2), UInt32(48000)),
    )
    expect_nonzero(
        "decoder_init_memory_f32(empty)",
        bridge.decoder_init_memory_f32(decoder, "", UInt64(0), UInt32(2), UInt32(48000)),
    )
    expect_nonzero(
        "decoder_seek_to_pcm_frame(before init)",
        bridge.decoder_seek_to_pcm_frame(decoder, UInt64(0)),
    )
    expect_negative(
        "decoder_read_probe_f32(before init)",
        bridge.decoder_read_probe_f32(decoder, UInt64(8)),
    )

    # Positive decoder contract (deterministic test asset generated by gate).
    var decoder_init_result = bridge.decoder_init_file_f32(
        decoder,
        test_wav,
        UInt32(2),
        UInt32(48000),
    )
    if decoder_init_result == 0:
        expect_zero(
            "decoder_seek_to_pcm_frame(after init)",
            bridge.decoder_seek_to_pcm_frame(decoder, UInt64(0)),
        )
        var probe_frames = bridge.decoder_read_probe_f32(decoder, UInt64(8))
        if probe_frames < 0:
            raise Error("decoder_read_probe_f32(after init) expected non-negative")
        expect_zero("decoder_uninit(after init)", bridge.decoder_uninit(decoder))

    # Deterministic encoder contracts.
    expect_nonzero(
        "encoder_init_wav_file_f32(channels=0)",
        bridge.encoder_init_wav_file_f32(encoder, "/tmp/mmj-contract-encoder-invalid.wav", UInt32(0), UInt32(48000)),
    )
    expect_nonzero(
        "encoder_init_wav_file_f32(sample_rate=0)",
        bridge.encoder_init_wav_file_f32(encoder, "/tmp/mmj-contract-encoder-invalid.wav", UInt32(2), UInt32(0)),
    )
    expect_nonzero(
        "encoder_write_silence_f32(before init)",
        bridge.encoder_write_silence_f32(encoder, UInt64(8)),
    )

    # Positive encoder contract with deterministic write path.
    var encoder_init_result = bridge.encoder_init_wav_file_f32(
        encoder,
        "/tmp/mmj-contract-encoder.wav",
        UInt32(2),
        UInt32(48000),
    )
    if encoder_init_result == 0:
        expect_zero("encoder_write_silence_f32(after init)", bridge.encoder_write_silence_f32(encoder, UInt64(16)))
        expect_zero("encoder_uninit(after init)", bridge.encoder_uninit(encoder))

    bridge.decoder_destroy(decoder)
    bridge.encoder_destroy(encoder)

    print("mojo decoder/encoder contract suite ok")
